version: "3"

x-var:
  - &env-common
    LANG: C.UTF-8
    TZ: Asia/Tokyo

services:
  app:
    hostname: app
    build: .
    environment:
      <<: *env-common
    ports:
      - 8000:8000
    volumes:
      - .:/live-hajimatter:cached
      - backend-deps:/live-hajimatter/backend/.venv:delegated
    tty: true

volumes:
  backend-deps:
